services:
  chamcong:
    image: chamcong
    build:
      context: .
      dockerfile: ChamCong/Dockerfile

  apiserver:
    image: apiserver
    build:
      context: .
      dockerfile: ApiServer/Dockerfile

